# Generated by Django 5.2.3 on 2025-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_anadir_categorias_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='ha_visto_animacion_premium',
            field=models.BooleanField(default=False),
        ),
    ]
