# Generated by Django 5.2.3 on 2025-07-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_suscripcion_ha_visto_animacion_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicio',
            name='viernes',
            field=models.BooleanField(default=True),
        ),
    ]
