# Generated by Django 5.2.3 on 2025-06-28 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(default='Desconocida', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Sin título', max_length=200),
        ),
    ]
