# Generated by Django 5.2.3 on 2025-07-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_servicio_domingo_servicio_hora_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='domingo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='viernes',
        ),
    ]
