# Generated by Django 5.2.3 on 2025-06-30 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_servicio_remove_task_project_turno_delete_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='cliente',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_minutos',
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('servicio', 'fecha', 'hora')},
        ),
        migrations.AddField(
            model_name='servicio',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200),
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario_apertura',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario_cierre',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_estandar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.RemoveField(
            model_name='turno',
            name='estado',
        ),
    ]
