# Generated by Django 5.2.3 on 2025-07-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_servicio_domingo_remove_servicio_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariolaboral',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (0, 'Domingo')]),
        ),
    ]
