# Generated by Django 5.2.3 on 2025-06-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_cliente_turno_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
