# Generated by Django 5.2.3 on 2025-07-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_horariolaboral_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='medio_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia / Alias / Mercado Pago'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito')], default='efectivo', help_text='El medio de pago elegido por el cliente.', max_length=20),
        ),
    ]
