# Generated by Django 5.2.3 on 2025-07-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador único para el código, ej: 'efectivo'", unique=True)),
                ('nombre_visible', models.CharField(help_text='El nombre que verá el usuario en el formulario', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='medios_de_pago_aceptados',
            field=models.ManyToManyField(blank=True, help_text='Selecciona los medios de pago que aceptas en tu negocio.', to='myapp.mediodepago'),
        ),
    ]
