# Generated by Django 5.2.3 on 2025-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_turno_usuario_servicio_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='visto_por_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
