# Generated by Django 5.2.3 on 2025-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_turno_visto_por_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=30, help_text='Duración del servicio en minutos'),
        ),
    ]
