# Generated by Django 5.2.3 on 2025-07-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_mediodepago_servicio_medios_de_pago_aceptados'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='medio_de_pago_final',
            field=models.CharField(blank=True, help_text='El medio de pago real con el que se cobró el turno.', max_length=50, null=True),
        ),
    ]
