# Generated by Django 5.2.3 on 2025-07-30 14:44

from django.db import migrations

def crear_perfiles_para_usuarios_existentes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    PerfilUsuario = apps.get_model('myapp', 'PerfilUsuario')

    usuarios_sin_perfil = User.objects.filter(perfil__isnull=True)

    perfiles_a_crear = []
    for usuario in usuarios_sin_perfil:
        perfiles_a_crear.append(PerfilUsuario(usuario=usuario))
    
    if perfiles_a_crear:
        PerfilUsuario.objects.bulk_create(perfiles_a_crear)
        print(f"\nSe han creado {len(perfiles_a_crear)} perfiles faltantes.")

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_turno_medio_de_pago_final'),
    ]

    operations = [
        migrations.RunPython(crear_perfiles_para_usuarios_existentes),
    ]
