# Generated by Django 5.2.3 on 2025-07-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_servicio_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='horario_cierre',
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('activo', models.BooleanField(default=True, help_text='Marcar si el servicio está abierto este día')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='myapp.servicio')),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('servicio', 'dia_semana')},
            },
        ),
    ]
