# Generated by Django 5.2.3 on 2025-07-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_crear_perfiles_faltantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duracion_buffer_minutos',
            field=models.PositiveIntegerField(default=15, help_text="Minutos de 'colchón' que se añadirán después de cada turno para preparación."),
        ),
    ]
