# Generated by Django 5.2.3 on 2025-07-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_dianodisponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ingreso_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ingreso monetario real generado por este turno.', max_digits=10, null=True),
        ),
    ]
