# Generated by Django 5.2.3 on 2025-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_servicio_duracion_buffer_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='color_slot',
            field=models.CharField(default='#4A4A4A', help_text='Color de fondo para los botones de horarios y servicios.', max_length=7),
        ),
        migrations.AddField(
            model_name='servicio',
            name='color_slot_seleccionado',
            field=models.CharField(default='#28a745', help_text='Color de fondo para los botones CUANDO están seleccionados.', max_length=7),
        ),
    ]
