# Generated by Django 5.2.3 on 2025-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_servicio_color_slot_servicio_color_slot_seleccionado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariolaboral',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='horariolaboral',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='descanso_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='descanso_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='tiene_descanso',
            field=models.BooleanField(default=False, help_text='Marcar si hay un descanso en medio de la jornada.'),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para desactivar esta regla temporalmente.'),
        ),
        migrations.AlterField(
            model_name='horariolaboral',
            name='dia_semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
