# Generated by Django 5.2.3 on 2025-08-01 01:35

from django.db import migrations

def transferir_datos_de_dia_semana(apps, schema_editor):
    HorarioLaboral = apps.get_model('myapp', 'HorarioLaboral') # Cambia 'myapp' si es necesario

    # Mapeo de número de día a nombre de campo
    # (Asegúrate de que estos números coincidan con los que usabas antes)
    dia_map = {
        1: 'lunes',
        2: 'martes',
        3: 'miercoles',
        4: 'jueves',
        5: 'viernes',
        6: 'sabado',
        0: 'domingo',
    }

    # Recorremos todos los horarios existentes
    for horario in HorarioLaboral.objects.all():
        if horario.dia_semana is not None:
            # Obtenemos el nombre del campo a activar (ej: 'lunes')
            nombre_campo_dia = dia_map.get(horario.dia_semana)
            
            if nombre_campo_dia:
                # Usamos setattr para poner el campo correspondiente en True
                # ej: setattr(horario, 'lunes', True) es lo mismo que horario.lunes = True
                setattr(horario, nombre_campo_dia, True)
                horario.save()
                print(f"Migrado horario ID {horario.id}: día {nombre_campo_dia} activado.")

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_horariolaboral_options_and_more'),
    ]

    operations = [
        migrations.RunPython(transferir_datos_de_dia_semana),
    ]
