# Generated by Django 5.2.3 on 2025-07-08 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_reseña'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='servicios_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
