# Generated by Django 5.2.3 on 2025-08-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_migrar_datos_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariolaboral',
            name='dia_semana',
        ),
    ]
