# Generated by Django 5.2.3 on 2025-07-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_servicio_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='color_fondo',
            field=models.CharField(default='#333333', help_text='Color de fondo de las tarjetas (ej: #333333)', max_length=7),
        ),
        migrations.AddField(
            model_name='servicio',
            name='color_primario',
            field=models.CharField(default='#007bff', help_text='Color principal (ej: #007bff)', max_length=7),
        ),
        migrations.AddField(
            model_name='servicio',
            name='footer_personalizado',
            field=models.TextField(blank=True, help_text='Texto o HTML simple para el footer de tu página.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_banner',
            field=models.ImageField(blank=True, help_text='Imagen grande para la cabecera', null=True, upload_to='banners/'),
        ),
    ]
