# Generated by Django 5.2.3 on 2025-07-14 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_servicio_color_fondo_servicio_color_primario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_servicios', to='myapp.servicio')),
            ],
        ),
    ]
