# Generated by Django 5.2.3 on 2025-08-02 00:49

from django.db import migrations
# Función que se ejecutará para crear los perfiles
def crear_perfiles_para_usuarios_existentes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    PerfilUsuario = apps.get_model('myapp', 'PerfilUsuario') # Reemplaza 'myapp' si tu app se llama diferente

    # Buscamos todos los usuarios que NO tienen un perfil
    usuarios_sin_perfil = User.objects.filter(perfil__isnull=True)
    
    # Creamos un perfil para cada uno de ellos
    for usuario in usuarios_sin_perfil:
        PerfilUsuario.objects.create(usuario=usuario)
        print(f"Creado perfil para el usuario: {usuario.username}")

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_horariolaboral_dia_semana'),
    ]

    operations = [
         migrations.RunPython(crear_perfiles_para_usuarios_existentes),
    ]
