# Generated by Django 5.2.3 on 2025-08-02 07:07

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_crear_perfiles_faltantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sube un logo para tu negocio (recomendado: cuadrado, ej. 400x400px, máx 1MB).', null=True, upload_to='logos/', validators=[myapp.models.validar_tamaño_maximo_img]),
        ),
    ]
