# Generated by Django 5.2.3 on 2025-07-14 07:03

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_subservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio_estandar',
        ),
        migrations.AddField(
            model_name='turno',
            name='duracion_total',
            field=models.PositiveIntegerField(default=30, help_text='Duración total calculada en minutos'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sub_servicios_solicitados',
            field=models.ManyToManyField(blank=True, to='myapp.subservicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen_banner',
            field=models.ImageField(blank=True, help_text='Imagen grande para la cabecera (máx 2MB)', null=True, upload_to='banners/', validators=[myapp.models.validar_tamaño_maximo_img]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='ingreso_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='myapp.servicio'),
        ),
    ]
