# Generated by Django 5.2.3 on 2025-08-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_servicio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='footer_facebook_url',
            field=models.CharField(blank=True, help_text='Solo el nombre de tu página (ej: cocacola)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='footer_instagram_url',
            field=models.CharField(blank=True, help_text='Solo tu nombre de usuario (sin @)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='footer_tiktok_url',
            field=models.CharField(blank=True, help_text='Solo tu nombre de usuario (con @)', max_length=100, null=True),
        ),
    ]
