# Generated by Django 5.2.3 on 2025-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_servicio_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='configuracion_inicial_completa',
            field=models.BooleanField(default=False),
        ),
    ]
