# Generated by Django 5.2.3 on 2025-08-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_servicio_footer_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dianodisponible',
            name='fecha',
        ),
        migrations.AddField(
            model_name='dianodisponible',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Opcional. Rellena este campo solo si quieres bloquear un rango de varios días.', null=True),
        ),
        migrations.AddField(
            model_name='dianodisponible',
            name='fecha_inicio',
            field=models.DateField(default=None, help_text='Día de inicio del bloqueo (o día único).'),
            preserve_default=False,
        ),
    ]
