# Generated by Django 5.2.3 on 2025-07-15 06:04

from django.db import migrations

# Lista de categorías iniciales que queremos crear
CATEGORIAS_INICIALES = [
    {"nombre": "Peluquerías y Barberías", "slug": "peluquerias-barberias"},
    {"nombre": "Belleza y Estética", "slug": "belleza-estetica"},
    {"nombre": "Salud y Bienestar", "slug": "salud-bienestar"},
    {"nombre": "Mascotas", "slug": "mascotas"},
    {"nombre": "Deportes y Fitness", "slug": "deportes-fitness"},
    {"nombre": "Clases y Tutorías", "slug": "clases-tutorias"},
    {"nombre": "Servicios Profesionales", "slug": "servicios-profesionales"},
]

def poblar_categorias(apps, schema_editor):
    """
    Esta función se ejecutará cuando apliquemos la migración.
    """
    # Obtenemos el modelo Categoria de esta versión de la historia de la app
    Categoria = apps.get_model('myapp', 'Categoria')
    for categoria_data in CATEGORIAS_INICIALES:
        # Creamos cada categoría si no existe ya
        Categoria.objects.get_or_create(
            nombre=categoria_data['nombre'],
            defaults={'slug': categoria_data['slug']}
        )

def despoblar_categorias(apps, schema_editor):
    """
    Esta función se ejecutaría si quisiéramos revertir la migración.
    """
    Categoria = apps.get_model('myapp', 'Categoria')
    nombres_a_borrar = [c['nombre'] for c in CATEGORIAS_INICIALES]
    Categoria.objects.filter(nombre__in=nombres_a_borrar).delete()


class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate de que esta dependencia apunte a tu última migración REAL de modelos
        ('myapp', '0020_categoria_servicio_categoria'), 
    ]

    operations = [
        migrations.RunPython(poblar_categorias, reverse_code=despoblar_categorias),
    ]