# Generated by Django 5.2.3 on 2025-08-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_dianodisponible_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianodisponible',
            name='motivo',
            field=models.CharField(blank=True, help_text='Ej: Vacaciones, Feriado', max_length=255),
        ),
    ]
