# Generated by Django 5.2.3 on 2025-07-16 04:06

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_poblar_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='configuracion_inicial_completa',
        ),
        migrations.AddField(
            model_name='servicio',
            name='tours_vistos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='color_fondo',
            field=models.CharField(default='#333333', help_text='Color de fondo', max_length=7),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='color_primario',
            field=models.CharField(default='#007bff', help_text='Color principal', max_length=7),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='footer_personalizado',
            field=models.TextField(blank=True, help_text='Texto o HTML simple para el footer'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen_banner',
            field=models.ImageField(blank=True, help_text='Banner (máx 2MB)', null=True, upload_to='banners/', validators=[myapp.models.validar_tamaño_maximo_img]),
        ),
    ]
