# Generated by Django 5.2.3 on 2025-07-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_servicio_configuracion_inicial_completa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='tours_vistos',
        ),
        migrations.AddField(
            model_name='servicio',
            name='onboarding_tour_completo',
            field=models.BooleanField(default=False),
        ),
    ]
