# Generated by Django 5.2.3 on 2025-08-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_profesional_user_account_alter_turno_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='anotaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Anotaciones Adicionales'),
        ),
    ]
