# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_servicio_tours_vistos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='onboarding_tour_completo',
            new_name='tour_completo',
        ),
    ]
