# Generated by Django 5.2.3 on 2025-09-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_turno_anotaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='medio_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito')], default='efectivo', help_text='El medio de pago elegido por el cliente.', max_length=20),
        ),
    ]
