# Generated by Django 5.2.3 on 2025-07-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_onboarding_tour_completo_servicio_tour_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='tour_completo',
            new_name='configuracion_inicial_completa',
        ),
    ]
