# Generated by Django 5.2.3 on 2025-07-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_tour_completo_servicio_configuracion_inicial_completa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Indica si el propietario tiene el pago al día y el servicio está habilitado.'),
        ),
    ]
