# Generated by Django 5.2.3 on 2025-07-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_servicio_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='footer_direccion',
            field=models.CharField(blank=True, help_text='Ej: Av. Siempreviva 742, Springfield', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='footer_email',
            field=models.EmailField(blank=True, help_text='El email de contacto de tu negocio.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='footer_facebook_url',
            field=models.URLField(blank=True, help_text='Pega aquí la URL completa de tu página de Facebook.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='footer_instagram_url',
            field=models.URLField(blank=True, help_text='Pega aquí la URL completa de tu perfil de Instagram.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='footer_telefono',
            field=models.CharField(blank=True, help_text='Ej: +54 9 11 1234-5678', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='footer_tiktok_url',
            field=models.URLField(blank=True, help_text='Pega aquí la URL completa de tu perfil de TikTok.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fuente_cuerpo',
            field=models.CharField(choices=[('Roboto, sans-serif', 'Simple y Moderna (Roboto)'), ('Open Sans, sans-serif', 'Clara y Amigable (Open Sans)'), ('Lato, sans-serif', 'Elegante y Profesional (Lato)'), ('Playfair Display, serif', 'Clásica y Sofisticada (Playfair Display)'), ('Montserrat, sans-serif', 'Audaz y Geométrica (Montserrat)')], default='Roboto, sans-serif', help_text='Elige la fuente para el texto general.', max_length=100),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fuente_titulos',
            field=models.CharField(choices=[('Roboto, sans-serif', 'Simple y Moderna (Roboto)'), ('Open Sans, sans-serif', 'Clara y Amigable (Open Sans)'), ('Lato, sans-serif', 'Elegante y Profesional (Lato)'), ('Playfair Display, serif', 'Clásica y Sofisticada (Playfair Display)'), ('Montserrat, sans-serif', 'Audaz y Geométrica (Montserrat)')], default='Montserrat, sans-serif', help_text='Elige la fuente para los títulos principales.', max_length=100),
        ),
    ]
