# Generated by Django 5.2.3 on 2025-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_servicio_footer_direccion_servicio_footer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='color_texto',
            field=models.CharField(default='#FFFFFF', help_text='Color para el texto principal. Elige un color oscuro si usas un fondo claro.', max_length=7),
        ),
    ]
