# Generated by Django 5.2.3 on 2025-07-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_servicio_color_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='slug',
            field=models.SlugField(blank=True, help_text='Generado automáticamente a partir del nombre para la URL.', max_length=120, null=True, unique=True),
        ),
    ]
