# Generated by Django 5.2.3 on 2025-07-27 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_servicio_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('free', 'Gratis'), ('pro', 'Profesional'), ('prime', 'Prime')], max_length=50, unique=True)),
                ('slug', models.SlugField(help_text="Se usa en las URLs. Ej: 'pro'", unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('stripe_monthly_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('allow_customization', models.BooleanField(default=False, help_text='Permite personalizar colores, fuentes y banner.')),
                ('allow_metrics', models.BooleanField(default=False, help_text='Permite acceder al dashboard de métricas.')),
                ('support_level', models.CharField(default='email', help_text="Nivel de soporte: 'email', 'chat', 'whatsapp'", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.plan')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
