# Generated by Django 5.2.3 on 2025-07-27 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_plan_suscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscripcion',
            old_name='current_period_end',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='stripe_subscription_id',
            new_name='mp_subscription_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_monthly_price_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='support_level',
        ),
        migrations.AddField(
            model_name='plan',
            name='mp_plan_id',
            field=models.CharField(blank=True, help_text='El ID del Plan de Suscripción creado en Mercado Pago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='allow_customization',
            field=models.BooleanField(default=False, help_text='Permite personalizar colores y banner.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones', to='myapp.plan'),
        ),
    ]
